### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by drkibitz** [ReSwift/ReSwift-Thunk#10]
I'm sorry if anyone takes offense of blunt statements, because I am grateful for this project, and ReSwift. This project is one of the smallest codebases in the entirety of my project, or any project I've worked on in recent memory. Seriously, what's the hold up of an actual 1.0.0 release?

**Comment by mjarvis** [comment]
@drkibitz The largest roadblock is contributor time. There are a few things needed to be done to release this, including migration steps from a 3rd party thunk library.
I've detailed some of the steps needed here: https://github.com/mikecole20/ReSwiftThunk/issues/7#issuecomment-442562097

If you find yourself with some time to contribute it would be much appreciated! Even making issues for each of those steps here would be helpful.

**Comment by drkibitz** [comment]
Thanks for your response . I think from what I just read, I can contribute to 3 of those steps. The rest are already done.
1. Add migration guide to this readme, maybe even add the old implementation and mark as deprecated
2. Add issue to archive the other repo.
3. I think issue can  already represent the issue to release a 1.0 version of this project

**Comment by DivineDominion** [comment]
@drkibitz If you contribute, that'd be great! Then I'll have a look at integrating existing code into this code base.
