### ISSUE TITLE
Unable to install ExpectThunk using Cocoapods

### ISSUE THREAD

**Issue by LunaCodeGirl** [ReSwift/ReSwift-Thunk#24]
Hey all, I seem to be stuck. First I tried using this Podfile to install `ExpectThunk`:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  use_frameworks!

  pod 'ReSwift'
  pod 'ReSwiftThunk'

  pod 'PromiseKit', '~> 6.8'

  target 'MyAppTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'ReSwiftThunk/ExpectThunk'
  end

end
```

That produced this error:

> [!] CocoaPods could not find compatible versions for pod "ReSwiftThunk/ExpectThunk":
  In Podfile:
    ReSwiftThunk/ExpectThunk
>    
>  None of your spec sources contain a spec satisfying the dependency:    `ReSwiftThunk/ExpectThunk`.

I noticed the note in the Readme on issues with nested targets, so I updated my Podfile to this:

```ruby
def common_pods
  pod 'ReSwift'
  pod 'PromiseKit', '~> 6.8'
end

target 'MyApp' do
  use_frameworks!

  common_pods

  pod 'ReSwiftThunk'
end

target 'MyAppTests' do
  common_pods

  pod 'Quick'
  pod 'Nimble'

  pod 'ReSwiftThunk/ExpectThunk'
end
```

That is producing the same error, which doesn't actually seem to be related to the nested target issue. 

Any suggestions?

**Comment by mjarvis** [comment]
`ExpectThunk` has not yet been included in a release. You'll need to specify the git repo & master branch in your `Podfile` to use it at this time.
