### ISSUE TITLE
Update podspec to support ReSwift 5.0.0

### ISSUE THREAD

**Issue by bdrobert** [ReSwift/ReSwift-Thunk#30]
The podspec s.dependency needs updated to support ReSwift 5.0.

**Comment by elishaterada** [comment]
The podspec still seem to reference 4.0:

https://github.com/CocoaPods/Specs/blob/master/Specs/8/d/b/ReSwiftThunk/1.1.0/ReSwiftThunk.podspec.json

**Comment by DivineDominion** [comment]
You're right! Will fix :)
