### ISSUE TITLE
v.1.2.0 CocoaPods release missing

### ISSUE THREAD

**Issue by okaverin** [ReSwift/ReSwift-Thunk#34]
v.1.2.0 is missing a git tag and a CocoaPods release

**Comment by DivineDominion** [comment]
We can't push the release unless the error shown in #33 is fixed :/ Tracking progress in #35 now.

If you can chime in with ideas, help is very welcome!

**Comment by DivineDominion** [comment]
I don't have write access to CocoaPods 😬  So we're waiting for @mjarvis for this release

**Comment by mjarvis** [comment]
released!
