### ISSUE TITLE
carthage build fails for non-iOS platforms

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift-Thunk#4]
Running initial `carthage bootstrap` or later `carthage build --platform mac`, the error I get is this:

> Failed to write to /Users/ctm/Downloads/test/Carthage/Build/Mac/ReSwift_Thunk.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ReSwift_Thunk.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/ctm/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/ReSwift-Thunk/9ff0068fc855efd3a1a8944056d8b0da41123a23/Build/Intermediates.noindex/ArchiveIntermediates/ReSwift-Thunk/BuildProductsPath/Release-iphoneos/ReSwift_Thunk.framework, NSFilePath=/Users/ctm/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/ReSwift-Thunk/9ff0068fc855efd3a1a8944056d8b0da41123a23/Build/Intermediates.noindex/ArchiveIntermediates/ReSwift-Thunk/BuildProductsPath/Release-iphoneos/ReSwift_Thunk.framework, NSUnderlyingError=0x7ffc38749d50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Note that the source path is `Build/Intermediates.noindex/ArchiveIntermediates/ReSwift-Thunk/BuildProductsPath/Release-iphoneos/ReSwift_Thunk.framework`, with emphasis on `Release-iphoneos`. A build product does exist in `Release/ReSwift_Thunk.framework`, so we have to get rid of the suffix somehow 🤔

Am investigating 💪

**Comment by dani-mp** [comment]
Hi, @DivineDominion. This https://github.com/ReSwift/ReSwift-Thunk/pull/7 fixed this issue, right?

**Comment by mjarvis** [comment]
Ping on this @DivineDominion or @danielmartinprieto if #7 fixed this issue we can close it off and we're just about ready for release.

**Comment by dani-mp** [comment]
@mjarvis I think it did, yes.

**Comment by mjarvis** [comment]
I'm going to consider this fixed, then, and proceed with steps towards release. If it turns out this was not fixed, we will likely get a new bug report at some point and can fix it in a future release.
