### ISSUE TITLE
ReSwift-Thunk on SPM has different module name

### ISSUE THREAD

**Issue by gert-janvercauteren** [ReSwift/ReSwift-Thunk#41]
Good morning,
I am migrating all my dependencies from cocoapods to SPM and I noticed the package for this library changes the import to include and _ so instead of `import ReSwiftThunk` we have to now import `import ReSwift_Thunk`. Was this change done on purpose?

If this change was on purpose we should consider renaming the module on Cocoapods etc to remain consistent across the board.

Happy to make a PR for this if I can help out in any way :)

**Comment by mjarvis** [comment]
For consistency with other ReSwift projects, it should be `import ReSwiftThunk`. Feel free to make a PR!

**Comment by fbernutz** [comment]
This was resolved with #42, right? In my opinion this can be closed.

**Comment by DivineDominion** [comment]
Good catch, thanks @fbernutz!
